insert into customer (CUSTOMERID,  DATE_OF_BIRTH,FIRST_NAME,LAST_NAME)
values(10001,'1980-01-15','firstName', 'lastName');


insert into address (ADDRESSID, ADDRESS_TYPE, ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3, SUBURB, POSTCODE, STATE, COUNTRY)
values(101,'HOME','ADDRESS LINE1', 'ADDRESS LINE2','ADDRESS LINE3', 'SUBURB', 'POSTCODE','STATE','COUNTRY');

